app: kafkid
appVer: "v0.0.1"
env: development

http:
  port: 8123
  readTimeout: 10
  writeTimeout: 10

logger:
  fileLocation: "logs/kafkid.log"
  fileMaxSize: 50 # megabytes
  fileMaxBackup: 10
  fileMaxAge: 30 # days
  stdout: true

kafka:
  addresses:
    - 127.0.0.1:9092

consumer:
  groupID: kafkid
  offsetFromNewest: true # false = from oldest offset in consumer group
  output:
    stdout: true
    fileLocation: consumer.log
